### ISSUE TITLE
/logout error

### ISSUE THREAD

**Issue by nvkelso** [nextzen/developers#5]
When loading `https://developers.nextzen.org/logout` I get:

`"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.'}"`

Which is kind irrelevant because I don't see an actual logout button on the site now. But if we were to add one (which is a good idea), it seems broken in current state.

**Comment by iandees** [comment]
The `/logout` URL only supports `POST` requests so that it is CSRF protected. You weren't supposed to go to the URL directly 😄.

I'll fix it so if you head to `/logout` directly you're presented with a button to click instead of an error page.
